### PR TITLE
fix(usePopper): fix initial overlay placement

### PR DESCRIPTION
**Pull request by kyletsang**
https://github.com/react-bootstrap/react-bootstrap/issues/6010

React overlays had this code, which I assume was to fix this issue.  I tested this locally in RB and it fixes the problem.

### CODE REVIEW

**Comment by jquense** [comment]
eh, the requirement for this is specific to the Overlay a consumer implements. Specifically bootstrap wants to to use 'display: block' to hide overlays, but then you run into the problem that you need to show the overlay before measuring it, hence the opacity and absolute positioning. Vanilla bootstrap doesn't have this problem because it imperatively shows, and then updates the popper instance, so it all happens in the same reflow/paint/whatever browser frame. React tho updates state and then popper sees and updates that _some time_ in the near feature, which can cause issues opr this tooltip design.

I think the correct generalized fix, is to clearly expose something on the returned popper state that indicates whether the popper element has been measured yet (since that happens async after it's "shown"). That way each consumer can decide what the correct way to handle this middle state is.

**Comment by kyletsang** [comment]
Currently the initial placement for tooltip and popover in bootstrap works ok because they already have the `position: absolute` defined in the initial styles. 

This is more to fix the generic case with bringing your own overlay.  Is it possible to handle it here via the initial styles (or any other method) so downstream consumers don't need to add additional logic to handle?  Are there downsides to this approach?

**Comment by jquense** [comment]
> Are there downsides to this approach?

yeah it's too prescriptive, it's entirely possible that someone will not want these styles applied to their element. I only know thought because it happened to me :P

**Comment by kyletsang** [comment]
> 
> 
> > Are there downsides to this approach?
> 
> yeah it's too prescriptive, it's entirely possible that someone will not want these styles applied to their element. I only know thought because it happened to me :P

Ah gotcha 😝 

Will re-think this later

**Comment by jquense** [comment]
it may be that the best solution is to add `popper.hasDoneInitialMeasure` and instruct users on how to consume that for custom overlays?

**Pull request closed without merging**
