### PR TITLE
fix(Button): add `href="#"` when no `href` provided for anchors

### LINKED ISSUE #44: Dropdown Toggle Accessibility
## Is your feature request related to a problem? Please describe

According to [these aria guidelines](https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html), "enter" is a valid key to toggle a dropdown, but doesn't appear to be supported in this package's Dropdown component.

## Describe the solution you'd like

Add a keydown event for the "enter" key to open a dropdown.

## Additional context

I'm happy to open a PR. My primary goal with this issue is to make sure its a valid request.

https://github.com/react-bootstrap/react-bootstrap/issues/5596#issuecomment-1016499010

### PR DESCRIPTION
**Pull request by kyletsang**
Fixes #44

Also converted AnchorSpec to TS

### CODE REVIEW

**Comment by jquense** [comment]
I think we removed this behavior for a reason...but I don't remember what it was. Do know we why this situation occurs? Is it that users just forget to add a href?

**Comment by kyletsang** [comment]
This was missed in RB since the nav dropdown toggle doesn't explicitly supply a href and user isn't able to.  

Since we are applying button semantics to an anchor, I think it makes sense to put it here?  If not, I can explicitly declare it on the RB side.

**Comment by jquense** [comment]
IDK honestly, lets add it and see if it causes issues.

**Review by jquense — APPROVED** [review]

**Comment by laneparton** [comment]
Might be a dumb question - but is this available as a release on the npm registry or do you have a schedule/idea of when it will be? :)

**Comment by kyletsang** [comment]
@laneparton I'll try and cut a release on Sunday night.

**Pull request merged**
