### PR TITLE
fix(usePopper): fix Popper modifier validation error

### PR DESCRIPTION
**Pull request by kyletsang**
Fixes this error:

Error: Uncaught Error: Popper: modifier "applyStyles" provided an invalid "phase" property, expected either beforeRead, read, afterRead, beforeMain, main, afterMain, beforeWrite, write, afterWrite but got "undefined"

### CODE REVIEW

**Comment by kyletsang** [comment]
Done in #10

**Comment by jquense** [comment]
doh sorry Kyle i didn't see this!

**Comment by kyletsang** [comment]
> 
> 
> doh sorry Kyle i didn't see this!

All good 😄  

I left you a few messages in Discord as well - looking to get some access to publishing restart packages and access to netlify/algolia to fix some RB docs issues.

Whenever you get a chance 👍

**Comment by jquense** [comment]
word, i'm a little under the weather ATM so if i don't get to it ping me again please

**Pull request closed without merging**
